---
# defaults file for ansible-master

python3_package: python3

# For Python 3, use python3-pip.
pip3_package: python3-pip
pip_executable: "{{ 'pip3' }}"

pip_install_packages:
  - name: ansible
    version: 2.9.13
